### ISSUE TITLE
Reduce enclave entry/exits

### ISSUE THREAD

**Issue by ryscheng** [oasislabs/oasis-core#10]
"After all the above, one of the biggest overheads that will remain is going to be the entry and exits to and from the enclave for each ecall and ocall. You can check Scone, Eleos and HotCalls papers for the mechanism details. For a faster turn around, you should directly check the code samples in project repositories for Eleos and HotCalls. Both of these projects have faster ocall libraries. "

High-level idea: Have a enclave thread that doesn't exit and a untrusted thread that doesn't enter. Then share memory between them.

I've checked out HotCalls, it seems to use a very simple shared memory approach to ECALLs. There is a simple shared data structure and one thread which is constantly in the enclave waiting for requests and processing them. So there is only one ECALL for starting the request processor.
https://github.com/oweisse/hot-calls/blob/master/include/hot_calls.h

We could implement something similar (probably in ekiden-enclave) and instead of using EDLs to define the interfaces we would do this ourselves.

How do we coordinate between trusted/untrusted portions when reading/writing shared memory? Are we going to have a lock? What if the untrusted portion is malicious?

**Comment by kostko** [comment]
This was done as part of the runtime rewrite based on Fortanix EDP.
