### ISSUE TITLE
Docker container development / private dependencies don't inherit credentials

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-core#1046]
The current cargo ekiden shell structure doesn't inherit authentication from the parent environment,
so cargo builds will fail by default since it doesn't have credentials.

It seems many of our developers copy their host private keys into the docker container, which is a bit suboptimal.
It also doesn't work when you are authenticating not with a direct "git managed key", but rather through an ssh-agent, e.g. offloading your key to a yubi key.

The most canonical yubikey setup i'm aware of is to forward the `~/.gnupg/S.scdaemon` unix socket into the container, and have a gpg-agent process running as the ssh-agent provider. (`S.gpg-agent.ssh` set as the `SSH_AUTH_SOCK`)

**Comment by kostko** [comment]
No longer exists.
