### ISSUE TITLE
protoc: incorrect package name

### ISSUE THREAD

**Issue by pro-wh** [oasislabs/oasis-core#1083]
in the registry API, there's more than one .proto file, and they aren't named the same thing as the package: entity.proto and runtime.proto. in this situation, if you import the registry API in another protobuf file, it gets compiled into things like `super::runtime::RuntimesResponse` instead of `super::registry::RuntimesResponse`.

cc @kostko

**Comment by Yawning** [comment]
There's no more proto files.
