### ISSUE TITLE
new node trust/verification of tendermint state

### ISSUE THREAD

**Issue by pro-wh** [oasislabs/oasis-core#1444]
When a new node joins the network, how does it come to know the current tendermint state?

Currently, we replay the blocks with tendermint's fast sync. Is this the right thing to do? Or is there some system of trust in place where we can, for example, verify only the latest block?

## Details

cross reference: https://github.com/oasislabs/private-ops/issues/799

cc @ryscheng 

## Acceptance Criteria
* discuss this question
* develop a plan for implementing a fast solution (possibly keep doing what we currently do)

**Comment by kostko** [comment]
Superseded by #2880.
