### ISSUE TITLE
Support for node re-registration 

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#1794]
From: https://github.com/oasislabs/ekiden/issues/1762#issuecomment-497312500

> Yawning commented 8 days ago
As a companion to this, there should be support for forcing re-registration (eg: the workerhost should trigger re-registration when recovering from the enclave crashing). The current re-registration logic is once per epoch transition with no retries, which will cause hilarity when the RAK gets regenerated.

**Comment by kostko** [comment]
Node re-registration is implemented with #2545. The only remaining part is on the consumer side, the committee bookkeeping component (group) needs to subscribe to registry node updates for any nodes that are part of the committee so it receives any updates.
