### ISSUE TITLE
Enable Tendermint Protocol Sentry in Ekiden Node

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#1828]
We need to enable an Ekiden Node to become a Sentry Node for Tendermint's Gossip protocol.

*Estimated cost: ~1 sprint*

## Details

[For more details on Tendermint's P2P protocol](https://github.com/tendermint/tendermint/tree/master/docs/spec/p2p)

## Acceptance Criteria
* An Ekiden Node can be run as a Sentry Node with persistent and private peers

**Comment by tjanez** [comment]
Implemented in #2300.
