### ISSUE TITLE
Enforce IAS proxy access control policy

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#1843]
~Depends on #1998, #1837, #2027~
Depends on #2039.

Currently anyone can use the IAS proxy. This should be changed by enforcing an access control policy that only allows registered nodes that need access.  The IAS proxy currently can ensure that it will only attest for pre-approved MRSIGNER/MRENCLAVE pairs, but the node registration process needs to be re-thought before more work on this can happen.

*Estimated cost: 5d*

**Comment by Yawning** [comment]
This is done.
