### ISSUE TITLE
HSM support design doc

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#1856]
We need to have HSM support to allow for Node Operators to protect the node keys properly.

## Details

Which HSMs do we support? Do we just support PKCS11? Do we support Cloud based HSMs? 

## Acceptance Criteria
* A design doc and work plan for getting HSM support in Ekiden are written and the epic/issues for the work is properly costed.

**Comment by Yawning** [comment]
Support can be done by extending the remote signer.  I'm not sure what more needs to be done here.
