### ISSUE TITLE
Progressive Deployment Design Doc

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#1882]
As an alternative to dump state and restart (See #1881) we need to support progressive deployments that allow for Node Operators to deploy updated binaries that will properly function as Nodes before and after a scheduled upgrade (the schedule would probably be based on block height). 

## Acceptance Criteria
* A design doc detailing how this would work is created.
* An epic is created and costed for the work required

**Comment by kostko** [comment]
Design document was done and discussed, epic for initial version in #2446.
