### ISSUE TITLE
tendermint: Replace iavl with our own mkvs

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#1898]
We use the tendermint iavl library to store state for everything, but there's no reason that we need to do so, and it may be nice to re-use the MKVS implementation that we have for our own storage at some point.

Required:
 * [x] Stop hashing keys (#1743)
 * [x] Garbage collection (for state pruning).
 * [x] Support for iterating over keys (prefix scan).

*Estimated cost: 1 sprint*

**Comment by kostko** [comment]
Another benefit is that our implementation is not sensitive to the order of updates so no sorting of keys is required. But we also need to evaluate performance first (would be beneficial for other purposes anyway).

**Comment by kostko** [comment]
Yet another benefit of this is that it would make it easier to write light consensus clients (they could just use our storage interface which already supports remote queries with proofs) -- in Go or in Rust.
