### ISSUE TITLE
Remove roothash migration code

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2097]
Once deployment tooling transitions to the BFT export/import tool, roothash migration tooling should not be needed anymore and can be removed.

**Comment by kostko** [comment]
Can this be removed now?

**Comment by ptrus** [comment]
I think it can be: the playback still "exports" the roothash (https://github.com/oasislabs/oasis-runtime/blob/master/genesis/bin/genesis_playback.rs#L303) though, but that is now used when generating benchmark genesis (and not directly imported using roothash import), but i think that doesn't block this?

**Comment by kostko** [comment]
> but that is now used when generating benchmark genesis (and not directly imported using roothash import), but i think that doesn't block this?

Yeah I don't think that can be avoided?
