### ISSUE TITLE
Remove granular role registration

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#2107]
_Re: Core Platform Meeting (2019/09/17)_

The registry currently allows granular registration of roles within the compute committee but this should be changed so that the per-runtime compute execution roles (txnscheduler/compute/merge nodes) are now a single "compute" role from the viewpoint of the registry.

The scheduler should still schedule individual roles as-is and would pick from all valid nodes registered with the new "compute" role.

**Comment by kostko** [comment]
> should we take the max of the hw requirements of non-validator compute and validators and merge the two categories together?

In light of recent architecture discussions, we should probably not combine validator and other compute node roles as we can imagine there being validator-only nodes and there being nodes that only run specific runtimes?

So it should be at least three classes:
* **Global:** Consensus nodes.
* **Per-runtime:** Compute execution nodes (txnscheduler/compute/merge).
* **Per-runtime:** Storage nodes.

And later also key manager nodes.

**Comment by kostko** [comment]
Updated the issue description to be more clear what needs to be done.

**Comment by pro-wh** [comment]
txnscheduler was not a per-runtime role

**Comment by kostko** [comment]
Oh just noticed this while implementing the runtime maintenance fee payments -- it seems that the committee scheduler currently does not take runtimes into account for merge and storage nodes.

This is incorrect and should be fixed (all these things should be per-runtime instead of global). Can you do it as part of this issue?
