### ISSUE TITLE
key manager: defer to tendermint state in client

### ISSUE THREAD

**Issue by pro-wh** [oasislabs/oasis-core#2197]
these mechanisms like watching node list and having in-memory mirror of keymanager ID -> status struct might be a scalability bottleneck. what's the lower bound of overhead for querying from our tendermint db? are our in-memory caches better than whatever caching tendermint has?

## Details

encountered in go/keymanager/client/client.go

from internal key manager audit

## Acceptance Criteria
* tbd

**Comment by kostko** [comment]
This has been changed in #2584.
