### ISSUE TITLE
key manager: zeroizing issues

### ISSUE THREAD

**Issue by pro-wh** [oasislabs/oasis-core#2204]
couple of thoughts about this:

- rust is heavy on moves, so is there something that's especially suited for stuff that we want to sanitize? maybe something with Pin and no automatic reallocation
- overall, we don't seem very consistent with zeroizing everwhere
- we might determine that it's not critical, because we keep the master secret persistently in memory anyway
- do our fixed-length types' `::from` rip out the buffer of a given vec? if not, those get dropped unzeroed
- the deoxysii object itself has a `zeroize`, but we never call it in our use.
- the deoxysii `seal` method takes owned vecs and drops them internally, which basically makes it impossible to wipe plaintext, and the plaintext in our case is keys.

## Details

encountered in keymanager-runtime/src/kdf.rs

from internal key manager audit

## Acceptance Criteria
* tbd

**Comment by Yawning** [comment]
I think this is a subset of #1683.
