### ISSUE TITLE
Extend entity descriptor with human-readable fields

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2234]
We should consider extending the entity descriptor with optional human-readable descriptor fields like name, website, security contact, etc. This would make it easier to compile a nice list of all entities participating in the system.

**Comment by kostko** [comment]
Yeah, it seems like this "public key to {metadata}" map can live outside the consensus layer (e.g., in a dashboard/explorer-like application). And entities can provide signed metadata to avoid spamming with random "claims".

**Comment by bennetyee** [comment]
One issue is that the human-label to public key map becomes security critical, since if it were subverted it would cause transaction targets to be mis-selected and such things to go awry.
