### ISSUE TITLE
Reward distribution mechanism

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2265]
We need a reward distribution mechanism.

*Estimated cost: ~2 sprints*

**Comment by kostko** [comment]
What else needs to be done here?

**Comment by pro-wh** [comment]
probably only refinement left. let's open separate issues for those

**Comment by kostko** [comment]
What about commission, do we need to support that? cc @peterjgilbert

**Comment by kostko** [comment]
I guess this is done now.
