### ISSUE TITLE
Gas fees for consensus txs

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2266]
To mitigate DoS by transaction spam we need to introduce gas fees for consensus transactions that can be performed by non-staked entities (e.g., staking transfers, escrow, reclaim escrow).

All operations which can only be performed by staked entities are exempt.

*Estimated cost: ~1 sprint*

**Comment by peterjgilbert** [comment]
We probably want a fixed gas cost per transaction (or per byte of transaction data), as well as a variable gas price (similar to the runtime gas model).
