### ISSUE TITLE
Persistent blacklist of known bad keys

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2272]
We should consider having a persistent blacklist of keys that were found to be provably misbehaving (e.g. nodes that were double signing things they shouldn't be).

Those keys should be stored in the consensus layer and be prevented from registering and/or participating in the system.

**Comment by Yawning** [comment]
While this isn't a bad idea in theory, with key generation being dirt cheap, I'm not sure if this solves much beyond the "all of our nodes have all this free storage space" problem.
