### ISSUE TITLE
go/tendermint/api: Use `EXISTS` tendermint query condition when available

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#2306]
There is a pending PR in the tendermint repo for adding an `EXISTS` query condition.  This will let us get rid of the `$(app).updated` event, and switch to per application `Event.Type` for nicer ABCI event generation/handling, and slightly smaller state.

**Comment by kostko** [comment]
The issue in question is https://github.com/tendermint/tendermint/pull/4077.

**Comment by kostko** [comment]
The upstream PR has been merged.
