### ISSUE TITLE
Establish policy on minimum safe set of validators

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2314]
Currently the scheduler will only halt consensus in case no validators could be elected (e.g., because they all expired). We should make it possible to specify (in the genesis block) a policy determining what the minimum safe validator set is.

If a minimum safe validator set cannot be elected, consensus should halt.

*Estimated cost: <1 sprint*

**Comment by Yawning** [comment]
Fixed by #2357.
