### ISSUE TITLE
e2e coverage broke make e2e-test and stdout of CLI

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2344]
PR https://github.com/oasislabs/oasis-core/pull/2229 broke two things:
* [x] running `make test-e2e` out of the box fails with entity ID not given error. It seems you need to run `cd go; make integrationrunner` first. Please either update the README or put this dependency in the Makefile.
* [x] getting the node binary with `net.Config().NodeBinary` in e2e tests returns the path to the `integrationrunner-wrapper.sh` now which also appends a human-readable coverage report to stdout. I am parsing stdout in my new `stake-cli` e2e tests and expect a strictly formatted output. Please either remove any output from the wrapper or provide a way to run `oasis-node` directly without the wrapper.
* [x] remove generated `coverage-e2e-XXXXXXXXXX.txt` files from the source directory. Putting them in `/tmp/oasis-test-runnerXXXXXXXXX` seems a better idea.

**Comment by pro-wh** [comment]
#2343 fixes the default invocation

**Comment by pro-wh** [comment]
the location of coverage output files is consistent with unit tests with coverage. both put them in the checkout. let's not change that as a one-off.

**Comment by pro-wh** [comment]
should run without the extra output now
