### ISSUE TITLE
Change staking account identifiers

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2346]
Currently staking account identifiers are simply the Ed25519 public keys. In order to support different kinds of accounts we should change how the account identifiers are defined.

We may want to use [Bech32](https://en.bitcoin.it/wiki/BIP_0173#Bech32).

**Comment by Yawning** [comment]
> We may want to use Bech32.

The human "friendly" encoding format is orthogonal to the actual identifier construction no?

**Comment by kostko** [comment]
Yes the internal representation can be different as long as we can decode all the required data from the input and map that onto the internal representation.

So I would be fine with still accepting public keys in the Bech32-encoded address' data field and having the same internal representation as is now. No need to hash the keys IMO?

This would still allow that we have different kinds of accounts in the future.

**Comment by kostko** [comment]
Actually I thought about this some more and I'm not sure how much sense doing this has. Different accounts will have different internal representations and it will probably make sense to have special operations for dealing with those instead of overloading the existing methods (e.g., transfer) with different account types.

**Comment by kostko** [comment]
Duplicate of #2870.
