### ISSUE TITLE
oasis-test-runner: Ensure each node gets its own set of log watcher handlers

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2355]
Currently, all created log watchers get the same copy of the configured log watcher handlers:
https://github.com/oasislabs/oasis-core/blob/f30484fa34ce0b7d333579540be1277be4fdae83/go/oasis-test-runner/oasis/oasis.go#L418-L422

**Comment by kostko** [comment]
Functions that generate handlers should probably return factories instead of the constructed handlers.
