### ISSUE TITLE
go/oasis-node/cmd/genesis: Add a self-delegation for the test entity

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#2358]
When creating a genesis file with the debug test entity enabled, the genesis provisioning tool injects a staking ledger entity for said debug test entity with one hundred billion general balance, and one hundred billion escrow balance.

This was done prior to delegation support, and a self delegation needs to be added as well.  While we are here, a component somewhere should enforce that the delegations and escrow balance matches, because this should trigger a hard failure due to invariant violation, instead of working.

**Comment by kostko** [comment]
> While we are here, a component somewhere should enforce that the delegations and escrow balance matches, because this should trigger a hard failure due to invariant violation, instead of working.

This should be done as part of #1633 (sanity checks for genesis state).

**Comment by kostko** [comment]
cc @abukosek
