### ISSUE TITLE
tendermint.private_peers should be only list of node IDs

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2387]
Based on [tendermint documentation](https://tendermint.com/docs/spec/p2p/config.html#private-peers) and [code](https://github.com/tendermint/tendermint/blob/bc572217c07b90ad9cee851f193aaa8e9557cbc7/node/node.go#L752) , the `tendermint.private_peers` flag should only contain the private node ids (not id@address as we do now).

Some fixes needed:
- in e2e tests we should only set IDs https://github.com/oasislabs/oasis-core/blob/e14f636dd4017e7cb6b48fc03e960265f0b7ca71/go/oasis-test-runner/oasis/args.go#L312
- flag description should be updated
https://github.com/oasislabs/oasis-core/blob/e14f636dd4017e7cb6b48fc03e960265f0b7ca71/go/consensus/tendermint/tendermint.go#L1169
- we might need to also lowercase the IDs (as we do for other IDs) since tendermint 
https://github.com/oasislabs/oasis-core/blob/e14f636dd4017e7cb6b48fc03e960265f0b7ca71/go/consensus/tendermint/tendermint.go#L778
- do some validation on the `tendermint.private_peers` parameter, to ensure it's indeed a list of IDs

**Comment by tjanez** [comment]
> - in e2e tests we should only set IDs
> - flag description should be updated
> - we might need to also lowercase the IDs (as we do for other IDs) since tendermint 

The first 3 are implemented by #2388.

> do some validation on the tendermint.private_peers parameter, to ensure it's indeed a list of IDs

I would defer this one to a separate issue that would systematically validate all tendermint flags (or even broader?) where strings need to correspond to a prescribed form.
