### ISSUE TITLE
Compute discrepancy in storage-sync E2E test

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2405]
Since ~11/19 a compute discrepancy often appears in the `storage-sync` E2E test.

**Comment by pro-wh** [comment]
the machinery seems to be working-as-intended, in a case where the compute committee is reelected between a local_insert and a local_get.

why would we write a test that expects compute nodes to agree on local storage?

**Comment by kostko** [comment]
Closing as it should be fixed by #2415. If not, we should reopen.
