### ISSUE TITLE
Testnet 1f6d2de0688998712cba3f642e68ae70075b4d93 Fails to Build

### ISSUE THREAD

**Issue by joesixpack** [oasislabs/oasis-core#2408]
git clone https://github.com/oasislabs/oasis-core
git checkout 1f6d2de0688998712cba3f642e68ae70075b4d93

   Compiling curve25519-dalek v1.2.3
   Compiling sha2 v0.8.0
   Compiling derive-new v0.5.8
   Compiling serde_derive v1.0.101
   Compiling serde_repr v0.1.5
   Compiling rand v0.7.2
   Compiling slog-json v2.3.0
   Compiling crossbeam-epoch v0.7.2
   Compiling zeroize_derive v0.1.0
   Compiling tempfile v3.1.0
   Compiling crossbeam-deque v0.7.1
   Compiling zeroize v0.6.0
   Compiling failure v0.1.6
   Compiling grpcio-compiler v0.5.0-alpha.2
   Compiling crossbeam v0.7.2
   Compiling deoxysii v0.2.0 (https://github.com/oasislabs/deoxysii-rust#4687841c)
   Compiling x25519-dalek v0.5.2
   Compiling ed25519-dalek v1.0.0-pre.2
   Compiling protoc-grpcio v1.1.0
   Compiling oasis-core-runtime v0.3.0-alpha (/home/j/oasis-core/runtime)
   Compiling oasis-core-client v0.3.0-alpha (/home/j/oasis-core/client)
error[E0423]: expected function, tuple struct or tuple variant, found struct `TxnBatch`
   --> runtime/src/transaction/dispatcher.rs:235:23
    |
235 |         let outputs = TxnBatch(
    |                       ^^^^^^^^ constructor is not visible here due to private fields

warning: use of deprecated item 'std::mem::uninitialized': use `mem::MaybeUninit` instead
  --> runtime/src/storage/mkvs/urkel/cache/lru_cache.rs:32:1
   |
32 | / intrusive_adapter!(
33 | |     CacheItemAdapter<Item> = Pin<Box<CacheItemBox<Item>>>:
34 | |         CacheItemBox<Item> { link: LinkedListLink }
35 | |         where Item: CacheItem + Default
36 | | );
   | |__^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0423`.
error: could not compile `oasis-core-runtime`.

To learn more, run the command again with --verbose.
Makefile:41: recipe for target 'runtimes' failed
make: *** [runtimes] Error 1

**Comment by kostko** [comment]
This issue has already been fixed in master (commit https://github.com/oasislabs/oasis-core/commit/54d03f9193b289b9cbe13ed33603012383375655) and only occurs with newer Rust toolchains. It should compile on nightly `2019-08-25`.
