### ISSUE TITLE
Bump fxmacker/cbor to 1.3.2

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2411]
A new version has been released which brings some correctness fixes and performance improvements. We are currently using an unreleased interim version.

**Comment by fxamacker** [comment]
I just released [fxamacker/cbor v1.3.2](https://github.com/fxamacker/cbor/releases).

It fixes issues discovered by an updated fuzzing program that includes "toarray" struct tag and more.

**Comment by kostko** [comment]
@fxamacker thanks for letting us know and thanks for your great library!
