### ISSUE TITLE
Nodes should use STUN/similar for discovery of externally connectable addresses

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-core#242]
Currently, node registration fills addresses for connection attempts with host-local interface IPs.

In practice, this doesn't work well on either the kubernetes multi-container environment, or on a WAN.

* [x] Stopgap: allow explicit specification of address a node should register as.
* [ ] Eventual: auto-discovery of externally visible interfaces.

**Comment by Yawning** [comment]
Don't think this should be done.  Explicit configuration is sufficient, and all of the auto-discovery protocols are horrific.
