### ISSUE TITLE
Remove Blocks field from roothash genesis

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2426]
The roothash genesis document includes a `Blocks` field that is used to populate the genesis block of a runtime that was just registered. This seems incorrect as the runtime structure already contains a `Genesis` field that has either a `StateRoot` or `State`.

I think we should:
* [x] Remove `Blocks` from roothash genesis.
* [x] Add `Round` to `RuntimeGenesis` and use that when initializing a runtime genesis block.
* [ ] ~Change `onNewRuntime` and `ForeignExecuteTx` to only use the runtime's `Genesis` structure.~
* [x] Update runtime-ethereum's genesis utilities to generate ~runtime descriptors instead of roothash state~ RuntimeGenesis map instead of Blocks.

**Comment by kostko** [comment]
This was done in #2462.

**Comment by matevz** [comment]
Note that oasis-runtime fix https://github.com/oasislabs/oasis-runtime/pull/958 for playback-genesis is blocked by https://github.com/oasislabs/oasis-runtime/issues/962
