### ISSUE TITLE
Genesis SanityCheck Addresses once existing deployments have cleaned up registry

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2428]
Since existing deployments currently include invalid P2P.IDs and addresses we cannot yet sanity check those fields in genesis as it would prevent doing a import/export deployment. After next deployment, check if registry state is ok and can be sanity checked.

Validate P2P.ID and Consensus/Committee/P2P addresses after existing deployments have cleared up registry.

**Comment by kostko** [comment]
While here, we should also deduplicate the node descriptor checks, possibly by having the registry doc's `SanityCheck` call `VerifyRegisterNodeArgs`.
