### ISSUE TITLE
speed up oasis-node pruning

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2432]
Currently, the node operators docs:
https://docs.oasis.dev/operators/joining-the-testnet.html#configuring-the-oasis-node

suggest running `oasis-node` with

```
tendermint:
  abci:
    prune:
      strategy: keep_n
      num_kept: 86400
```

This resulted in processing 3-4 blocks per second for catching up the network on my local PC with SSD. When I set the prune strategy to `none`, the throughput increased to ~30 blocks/s which is a huge leap.

I suggest we look into speeding up the prunning operation. Maybe we should prune the tree in a batch (e.g. every 1000 blocks?). Do we have any info on how much space prunning actually saves? Or maybe we use a hybrid approach where for catching up the network, we don't do prunning, and for just following it, we can prune each block?

**Comment by Yawning** [comment]
This is slow because using the pruner requires 1 db lookup and a mountain of deletes per block.  I'm not sure if batching would actually save all that much, the lookup is probably fairly cheap, the delete(s) are likely not.

> Do we have any info on how much space prunning actually saves?

 A lot.  That's why there's a pruner in the first place.

> Or maybe we use a hybrid approach where for catching up the network, we don't do prunning, and for just following it, we can prune each block?

So if I spin up a node when the network has been running for a month, I need to store every single ABCI state version for all of history up to the time I'm caught up?  That's stupid.

**Comment by matevz** [comment]
After 3 days, the serverdir is 9.2GiB big (623K blocks) and I decided to run `oasis-node` with `keep_n` strategy. I'm getting very slow prune notifications now (every two seconds):
```
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40157,"ts":"2019-11-27T06:29:10.022365875Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40158,"ts":"2019-11-27T06:29:12.048162566Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40159,"ts":"2019-11-27T06:29:14.068497576Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40160,"ts":"2019-11-27T06:29:16.108130267Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40161,"ts":"2019-11-27T06:29:18.12803558Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40162,"ts":"2019-11-27T06:29:20.146050691Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40163,"ts":"2019-11-27T06:29:22.171625901Z"}
{"caller":"prune.go:138","latest_version":623404,"level":"debug","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":40164,"ts":"2019-11-27T06:29:24.220972902Z"
```

The node will never be synced this way, so I disabled prunning.

**Comment by kostko** [comment]
This was done.
