### ISSUE TITLE
make operators have to sign blocks to get the staking reward

### ISSUE THREAD

**Issue by pro-wh** [oasislabs/oasis-core#2434]
##### SUMMARY

we want a feature where we require liveness to be eligible for the staking reward. for that, the entity needs to have a node that signed at least some fraction of the blocks in an epoch.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

go/consensus/tendermint/apps/staking

**Comment by kostko** [comment]
This was done.
