### ISSUE TITLE
build: Make the `go generate` step optional

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#2473]
Once #2436 is merged the only protobuf file used will be `./common/sgx/aesm/aesm_proto.pb`.

While it will be useful to maintain the make target to allow easy regeneration of the corresponding file, I would be in favor of just committing the generated  artifact into the repository so that `go generate` (and the Go protobuf compiler) is no longer mandatory for 99.9% of the users.

**Comment by kostko** [comment]
Done in #2489.
