### ISSUE TITLE
Hash should be base64 encoded in JSON

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2476]
Export hash.Hash to JSON as string.

Currently, it's exported as array of bytes, for example
```"state_root":[217,195,97,253,63,21,161,178,145,7,97,119,244,3,68,229,186,166,212,28,194,165,17,0,134,211,10,91,142,3,135,115]```
It should be exported as a base64 encoded string, like ```"state_root":"jycFqjlMlRtaL9QhhK9gqVezw4Lp4Kro34MSH4YggS8="```

**Comment by kostko** [comment]
This is probably the result of switching the codec library with the built-in one which doesn't use Base64 by default for types that implement `BinaryMarshaler`. We probably need to go around and add `TextMarshaler` implementations to our types.

**Comment by Yawning** [comment]
Increasing the priority of this because, the export format should be concrete sooner rather than later.

**Comment by matevz** [comment]
Do we also need to fix rust implementation anywhere?

**Comment by Yawning** [comment]
> Do we also need to fix rust implementation anywhere?

If the rust code uses something that isn't CBOR, then yes, but as far as I am aware, this is not the case.

**Comment by matevz** [comment]
This is used by `genesis-playback` for generating genesis_dump.json: https://github.com/oasislabs/oasis-core/blob/master/runtime/src/common/crypto/hash.rs#L6

**Comment by matevz** [comment]
This is now also correctly implemented in rust as part of https://github.com/oasislabs/oasis-core/pull/2462
