### ISSUE TITLE
Incorrect permission suggestion in error message

### ISSUE THREAD

**Issue by JonasPf** [oasislabs/oasis-core#2485]
When launching a node and the directory has incorrect permissions, I get the following message:

`common/Mkdir: path '/serverdir/node' has invalid permissions: -rw-r--r--. Expected permissions: 448`

The expected permissions look wrong to me. 448 is not a valid permission value in Unix.

**Comment by JonasPf** [comment]
Note that decimal 448 == octal 700. So it's strictly speaking still correct, just confusing because we typically use octal everywhere (e.g. chmod expects it in octal).

**Comment by kostko** [comment]
Which revision, is this on master?

**Comment by kostko** [comment]
I believe this was already fixed in a74913bae397ae86925c44989c94ab5fee59889c, please confirm which Git revision you are using.

**Comment by JonasPf** [comment]
I'm was using this binary: https://github.com/oasislabs/public-testnet-artifacts/releases/download/2019-11-26/oasis-node-linux-amd64.zip

Does that help?

**Comment by kostko** [comment]
Yeah, so this issue has been fixed in a more recent version. The current public testnet uses [a later version](https://docs.oasis.dev/operators/current-testnet-parameters.html) (see "Oasis Core commit SHA" and/or the linked "oasis-node Binaries" on that link)  that should already contain the fix.
