### ISSUE TITLE
Add more txsource workloads

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2506]
We should add more [txsource workloads](https://github.com/oasislabs/oasis-core/tree/master/go/oasis-node/cmd/debug/txsource/workload) to test out the system during longer term runs, specifically:

* [x] Delegation workloads
* [x] changing the commission schedule workload
* [x] Registry workloads.
* [x] Runtime workloads.

We should also consider using a genesis block which uses gas fees and rewards to test out those parts of the code.

**Comment by kostko** [comment]
We should also add transactions that add randomized additional fields as payloads, e.g. see #2708.

**Comment by kostko** [comment]
Also we should have stress tests that send lots of transactions in parallel every once in a while, so we test with large blocks.

**Comment by kostko** [comment]
Based on a bug discovered in #2708, we should test with oversized transactions and also restart (some) validator nodes while the long-term txsource test is running.

**Comment by kostko** [comment]
* [ ] We should also have some workloads that perform various historic queries using our exposed APIs and make sure the responses make sense.

**Comment by ptrus** [comment]
done in all the linked PRs
