### ISSUE TITLE
Add registry subcommand to verify if the node is properly registered

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2508]
##### SUMMARY

At the moment, instructions for verifying if a node is properly registered on the network are quite tedious and verbose.

Here is a copy from the [current Node Operator Docs](https://docs.oasis.dev/operators/joining-the-testnet.html#checking-that-your-node-is-properly-registered):

> To ensure that your node is properly connected as a validator on the network,
> you can check if you see the node's identity in the registry's node list.
> Unfortunately, at this time this is a bit of a manual process.
> 
> #### Getting the Node's consensus_pub.pem Identity
> 
> ```bash
> cat /serverdir/node/consensus_pub.pem
> ```
> 
> This will look like:
> 
> ```text
> -----BEGIN ED25519 PUBLIC KEY-----
> s+vZ71qeZnlq0HmQSDBiWn2OKcy3fXOuPMu76/5GkUI=
> -----END ED25519 PUBLIC KEY-----
> ```
> 
> You should search the registry's node list for this ID, e.g.
> `s+vZ71qeZnlq0HmQSDBiWn2OKcy3fXOuPMu76/5GkUI=`, and set it as environment
> variable:
> 
> ```bash
> NODE_CONSENSUS_ID="<NODE-CONSENSUS-ID>"
> ```
> 
> replacing `<NODE_CONSENSUS_ID>` with your node's `consensus_pub.pem` identity.
> 
> #### Searching for the Node's Identity
> 
> To check if the node is properly registered, run the following command:
> 
> ```bash
> oasis-node registry node list -v -a unix:/serverdir/node/internal.sock | grep $NODE_CONSENSUS_ID
> ```
> 
> If `grep` found your ID, then you're properly connected!

A `registry node` subcommand, e.g. `registry node check-registered`, would make this task a lot more convenient.

##### ISSUE TYPE
- Feature Idea

**Comment by Yawning** [comment]
This seems like bloat to me.  There is a command to list currently registered nodes.  There are multiple ways on any sensible system to search.
