### ISSUE TITLE
Add key manager policy document submission

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2516]
As noted in #1846 we need to add key manager policy document submission to the consensus layer in order to support upgrades without going through a dump/restore cycle.

**Comment by Yawning** [comment]
This needs policy decisions about who can submit the new policy document, and if end-users can run their own key manager instance for their own runtimes, how the consensus layer is supposed to enforce policy signature validation.

**Comment by tjanez** [comment]
This has been implemented in #2636.
