### ISSUE TITLE
runtime: Stop hardcoding runtime IDs into enclave binaries

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#2519]
Currently runtime IDs are hardcoded at compile time into the binary.  While this works, it is not all that flexible, and could be passed in at instantiation time.

AFAIK, env vars etc were not supported by the SGX interface so this probably requires another RPC call...

https://github.com/oasislabs/oasis-core/blob/494c12e0451d377736ff62628c78150d8839061a/tests/runtimes/simple-keyvalue/src/main.rs#L248

**Comment by kostko** [comment]
Related to https://github.com/oasislabs/oasis-core/issues/1739#issuecomment-506937308? Probably close that issue and keep everything here.
