### ISSUE TITLE
Assign enum values greater than 0

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2527]
Currently, `enum` values in both go and rust code mostly start counting from `0` (e.g. `KindCompute = 0`, `KindKeyManager = 1`). This caused troubles in the past, for example when object you were looking for in Tendermint state or a tree didn't exist, the object was initialized with default values and random stuff was starting to appear in the logs.

For sanity, always start counting enum values from `1` and reserve `0` for `Invalid`.

**Comment by kostko** [comment]
> For sanity, always start counting enum values from 1 and reserve 0 for Undefined.

So `0` shouldn't be undefined it should be invalid and explicitly rejected.
