### ISSUE TITLE
registry: avoid storing full tls certificates

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2556]
Currently we store whole certificates in registry, during #2475 an idea came up that we could potentially only store certificate hashes:

> ...But I guess the ony way to avoid it would be to completely override how TLS authentication is performed so that only certificate hashes would be compared ...

Taken from: https://github.com/oasislabs/oasis-core/pull/2475#discussion_r360342043

Should probably at least evaluate the approach.

**Comment by kostko** [comment]
With `google.golang.org/grpc/security/advancedtls` (see #2822) being a thing, this should be easy to do.

**Comment by kostko** [comment]
Instead of comparing certificate hashes we could just verify Ed25519 public keys. This would also simplify configuring certificates via the CLI/config as a public key is small compared to a certificate.
