### ISSUE TITLE
Confusing about the backend in the oasis-core

### ISSUE THREAD

**Issue by samohyes** [oasislabs/oasis-core#2568]
I am reading the source code of oasis-core and it makes me confused because it looks like the code is interacting with some backend service(which might be implemented in rust?). For instance, the codes here
https://github.com/oasislabs/oasis-core/blob/master/go/consensus/api/submission.go#L103

`backend.SubmitTx(ctx, sigTx)`

I can't really find where the tx is submitted to in the go directory. Is it submitted to some code in rust?

Thanks.

**Comment by kostko** [comment]
Sorry but GitHub issues are not a support forum, feel free to ask/discuss on Community Slack instead.
