### ISSUE TITLE
Skip some CI steps based on pull request's changes

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2573]
##### SUMMARY
When one makes a pull request that e.g. only adds documentation or assembles the Change Log from fragments, all the *heavy* Buildkite pipeline steps (e.g. Go/Rust building, Go tests, E2E tests) should be skipped.

##### ISSUE TYPE
- Ops

**Comment by pro-wh** [comment]
Can someone help post some examples of documentation-only changes?

I have found these for change log things:
c6742fdfbec72db6717494916658e8fa510301b5
