### ISSUE TITLE
go/genesis: The tests aren't actually being ran at all

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#2589]
Nothing actually calls the genesis document tests that live under `go/genesis/tests`.

There isn't really a reason why they need to live in a separate test driver either (unlike the consensus backed tests) since the test document should be consensus backend agnostic, so maybe refactor the tests out to `go/genesis/genesis_tests.go`.

Additionally, due to the tests not being ran at all, the test cases have rotted, and need to be fixed.

**Comment by kostko** [comment]
Ooops :-)
