### ISSUE TITLE
Genesis import fails for expired nodes

### ISSUE THREAD

**Issue by peterjgilbert** [oasislabs/oasis-core#2598]
Genesis import fails when the registry contains expired nodes:
```
level=error module=tendermint/registry caller=genesis.go:83 ts=2020-01-25T22:24:31.352771Z msg="InitChain: failed to register node" err="registry: node expired" node="unsupported value type"
level=error module=abci-mux caller=mux.go:433 ts=2020-01-25T22:24:31.352813Z msg="InitChain: fatal error in application" err="registry: genesis node registration failure: registry: node expired" app=200_registry
```

This is an issue because nodes are kept in the registry after expiring for the debonding period.

**Comment by peterjgilbert** [comment]
Example of affected genesis dump attached:
[questnet-dump.tar.gz](https://github.com/oasislabs/oasis-core/files/4112976/questnet-dump.tar.gz)

**Comment by Yawning** [comment]
I just did this in my branch since I'm messing with the registry code anyway.
