### ISSUE TITLE
go/extra/stats stops with error "version does not exist"

### ISSUE THREAD

**Issue by JonasPf** [oasislabs/oasis-core#2616]
##### SUMMARY

go/extra/stats does not work in the current testnet when started from very early blocks. It works ok with `--start-block 90000`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

go/extra/stats

##### OASIS NODE VERSION

```
Software version: 20.1.2
Runtime protocol version: 0.10.0
Consensus protocol version: 0.22.0
Committee protocol version: 0.7.0
Tendermint core version: 0.32.8
ABCI library version: 0.16.1
```

##### STEPS TO REPRODUCE

```
stats entity-signatures -a unix:/serverdir/node/internal.sock --start-block 1
```

##### ACTUAL RESULTS

```
ts=2020-01-29T17:19:04.075938413Z level=error module=cmd/stats caller=stats.go:268 msg="failed to query registry" err="rpc error: code = Unknown desc = version does not exist" height=2
```

##### EXPECTED RESULTS

The list of validators with their stats.

**Comment by JonasPf** [comment]
Looks like this could be caused by my pruning settings (thanks Peter for the tip):

```
tendermint:
  abci:
    prune:
      strategy: keep_n
      num_kept: 86400
```

**Comment by kostko** [comment]
Yeah, if you prune history then anything that has been pruned will not be available.
