### ISSUE TITLE
Move storage/mkvs/urkel to just storage/mkvs

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2657]
The MKVS implementation has been changed from the initial "Urkel tree" structure and it is no longer an actual "Urkel tree" so having "urkel" in its name is just confusing.

A similar rename should happen both in Go (under `go/`) and Rust (under `runtime/src/`).

**Comment by pro-wh** [comment]
what is it now?

**Comment by kostko** [comment]
A merklized patricia trie variant, just not exactly urkel tree.
