### ISSUE TITLE
Stake threshold for nodes with no roles

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2660]
Should we consider adding a stake threshold for nodes that register with no roles? Currently a node can register with no roles and not require any additional stake beyond the "entity threshold" for its entity.

**Comment by Yawning** [comment]
Yes, because descriptors take up consensus state.

**Comment by pro-wh** [comment]
https://github.com/oasislabs/oasis-core/blob/master/go/registry/api/api.go#L468 We don't allow them to register.

**Comment by kostko** [comment]
Ooops :-)
