### ISSUE TITLE
Bump minimum golang version to 1.13.8

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2689]
Recent versions contain security-related fixes in the Go runtime.

**Comment by tjanez** [comment]
I would like to note that the [`release` GitHub Actions workflow](https://github.com/oasislabs/oasis-core/actions?query=workflow:release) currently automatically uses the latest Go 1.13.x release:

https://github.com/oasislabs/oasis-core/blob/ab684b462b77869080c8ac6cf4f4c2c0abb3e25c/.github/workflows/release.yml#L21-L24
