### ISSUE TITLE
Show Go version used to build oasis-node in --version

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2730]
##### SUMMARY
Currently, running `oasis-node --version` outputs:
```
Software version: 20.3.2
Runtime protocol version: 0.11.0
Consensus protocol version: 0.23.0
Committee protocol version: 0.7.0
Tendermint core version: 0.32.8
ABCI library version: 0.16.1
```

It would be useful if `--version` also outputted the exact Go version used to build the binary (e.g. 1.13.8) so users would know:
- If the binary needs to be rebuilt with a newer Go version due to security fixes to standard library packages.
- Which Go version was used to build the binary so they can use this version to reproduce the build from source themselves.
  Note that the latter is not yet fully supported, see #2596 for more details.

##### ISSUE TYPE
- Feature Idea

**Comment by Yawning** [comment]
https://golang.org/pkg/runtime/#Version
