### ISSUE TITLE
Expose NodeByConsensusAddress via gRPC

### ISSUE THREAD

**Issue by silentlight** [oasislabs/oasis-core#2739]
##### SUMMARY
Please expose https://github.com/oasislabs/oasis-core/blob/master/go/consensus/tendermint/apps/registry/state/state.go#L183 in the gRPC api

##### ISSUE TYPE
- It is needed for getting a node information from validators endpoint

##### COMPONENT NAME
go/registry/api

**Comment by kostko** [comment]
An alternative is to make `GetValidators` return node identifiers or descriptors.

**Comment by Yawning** [comment]
Implemented.
