### ISSUE TITLE
Open Tendermint port 26657 to be able to access Tendermint Rest Interaface.

### ISSUE THREAD

**Issue by VitalyVolozhinov** [oasislabs/oasis-core#2768]
For the development of a monitoring and alerting tool it would be greatly helpful if the port was exposed so that I could access something like this : https://docs.tendermint.com/master/rpc/#/Websocket . Thank you.

**Comment by kostko** [comment]
We have our own RPC APIs that are exposed via the internal AF_LOCAL socket located in the node's data directory (called `internal.sock`). The used RPC protocol is gRPC with the CBOR codec and the exposed APIs try to be as agnostic to the underlying consensus protocol as possible (yes, we currently do use Tendermint, but we want to expose as little of that directly as possible).

These RPC APIs will never be exposed directly via TCP as some can be unsafe to use -- if you need this for a specific use case, a proxy should handle that translation, performing things like authentication, access control, rate limiting, etc.

If there is something specific missing from our RPC APIs, please file a more specific issue. At the moment there is no RPC-specific documentation besides E2E tests, example CLI utilities and the GoDoc reference for packages implementing the APIs.
