### ISSUE TITLE
Additional artifacts in oasis-core releases

### ISSUE THREAD

**Issue by peterjgilbert** [oasislabs/oasis-core#2780]
To facilitate runtime development, we should consider adding artifacts needed for testing runtimes to `oasis-core` releases:
- oasis-net-runner
- oasis-core-runtime-loader

**Comment by ptrus** [comment]
I think that with this we should also be able to retire the existing oasis-core docker pipeline and use the released artifacts when building the oasis-runtime docker image (instead of building it on top of the oasis-core image https://github.com/oasislabs/oasis-runtime/issues/937).
