### ISSUE TITLE
Docker images don't support current rust

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-core#280]
Something about SGX strangeness means we can't update rust past the march nightly.
There's also a stable sgx sdk that came out recently that claims to work against rust-stable. maybe we should use that as the basis of our development so stuff breaks less?

Needless to say, our dev environment / docker setup remains precarious, and as we continue to face the need of adding dependencies / changing it, we're going to end up spending a lot of time flailing against rust flakiness until we get somewhere saner.

**Comment by tjanez** [comment]
@kostko, @nhynes, any updates regarding the possibility of using a stable Rust version since @nhynes's comment in https://github.com/oasislabs/oasis-core/issues/297#issuecomment-423867480 from Sep 2018?

**Comment by kostko** [comment]
I think we cannot use it due to some unstable features required for Deoxys-II (asm?) and possibly something in the runtime library as well.

**Comment by tjanez** [comment]
I though so, thanks for your explanation.

Closing this. If someone is motivated to switch to a stable Rust versions in the future, he should file a new issue.
