### ISSUE TITLE
Report additional metrics to prometheus

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#2842]
We should consider adding at least the following consensus-layer metrics:

* [x] Current epoch number
* [x] IsRegistered
* [x] Blocks voted for by your node or something similar (just a way to determine if you're voting) -- for this we should check if there is anything existing from the Tendermint side.

**Comment by matevz** [comment]
kostko suggested two metrics for votes counting:
- how many times the node voted and the vote got included
- how many times the node proposed a block (was a proposer)
