### ISSUE TITLE
extra stats tools problem

### ISSUE THREAD

**Issue by wjdfx** [oasislabs/oasis-core#2854]
##### SUMMARY

1、all signatures is 0

oasis-core/go/extra/stats/stats entity-signatures -a unix:/mnt/serverdir/node/internal.sock --start-block 0 --end-block 5

|1    |7hAEASOPAKuePwArPtGlcg3nnaipRdgqb0hESkA7Jso=                    |     1|         0|                  3|               150|
|2    |FATFD8gST26YTWtJ4gJnWS1xoKPw7/nQm8bBtm2aedA=                    |     1|         0|                  1|                50|
|3    |kNh+IWc1PwgOfN2tld2T+0iI8SweaGuhf6mxHRol5oQ=                    |     1|         0|                  1|                50|
|4    |J8LlFtBQN63j5iRm3WNQKedY045yBkgTzEkR4eV6NyM=                    |     0|         0|                  0|                 0|
|5    |57ASGqcbEAyRoKS/hKI8rOiRUMI02oQHBIXnoG+hlEA=                    |     0|         0|                  0|                 0|
.....

2、some block number will show error

/oasis-core/go/extra/stats/stats entity-signatures -a unix:/mnt/serverdir/node/internal.sock --start-block 4785 --end-block 4786
ts=2020-04-17T15:54:57.317711465Z level=error module=cmd/stats caller=stats.go:315 msg="failure adding signature" err="missing node address map, address: B55C799B4E7F5ED9A6C6061BC7BD7851BE6C8598"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
go/extra/stats/stats

##### OASIS NODE VERSION

```
git branch
* (HEAD detached at v20.5)

oasis-node --version
Software version: 20.5
Runtime protocol version: 0.13.0
Consensus protocol version: 0.24.0
Committee protocol version: 0.9.0
Tendermint core version: 0.32.10
ABCI library version: 0.16.1
Go toolchain version: 1.13.10

```

##### OS / ENVIRONMENT

Go toolchain version: 1.13.10

```/oasis-core/go/extra/stats/stats entity-signatures -a unix:/mnt/serverdir/node/internal.sock --start-block 4785 --end-block 4786
ts=2020-04-17T15:54:57.317711465Z level=error module=cmd/stats caller=stats.go:315 msg="failure adding signature" err="missing node address map, address: B55C799B4E7F5ED9A6C6061BC7BD7851BE6C8598"

```

**Comment by SmartStake** [comment]
for me as well, the stats tool was working till block 4783 (with 0 signatures). When pulling data for 4783 to 5783 blocks, the tool fails with the same error as above.

**Comment by ptrus** [comment]
Hey, I can also reproduce the problem, will look into fixing it.

**Comment by ptrus** [comment]
Thanks for the report, this has been fixed both in [master](https://github.com/oasislabs/oasis-core/pull/2856) & backported to the [20.5.x](https://github.com/oasislabs/oasis-core/pull/2857) branch. 

For running it on the questnet, please build the `stats` tool on the latest revision of the [stable/20.5.x branch](https://github.com/oasislabs/oasis-core/tree/stable/20.5.x) and run the stats tool again (no changes to the node itself are needed, so you don't need to update the node, just the stats tool).
