### ISSUE TITLE
Cannot set default values for E2E Scenarios Parameters 

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2897]
`Parameters()` methods always create new flagset instances, for example:
https://github.com/oasislabs/oasis-core/blob/35b7f62efec57e7fe638ad0aeee8e32962dbfc47/go/oasis-test-runner/scenario/e2e/e2e.go#L56-L61

That is problematic in conjunction with:
https://github.com/oasislabs/oasis-core/blob/35b7f62efec57e7fe638ad0aeee8e32962dbfc47/go/oasis-test-runner/cmd/root.go#L130-L138

IF a flag doesn't set existing parameter state as the default value, e.g.:
`fs.StringVar(&sc.nodeBinary, cfgNodeBinary, "<some-default>", "path to the node binary")`

The parameter will get overridden with the default value every time `Parameters()` is called. 

---

Suggested fix:
`Parameters()` methods creating new flagset instances is wrong, instead the flagset should be stored in the scenario struct and `Parameters()` should just return the stored flagset. However, `Clone()` should create a new instance of the flagset.

**Comment by matevz** [comment]
Actually the way `Parameters()` should currently be implemented is by calling `fs.*Var()` helper functions with reference to the struct member as the first argument. Default value must be previously defined during struct initialization and this variable value should be passed to the `fs.*Var()` function as the third argument like this: https://github.com/oasislabs/oasis-core/blob/35b7f62efec57e7fe638ad0aeee8e32962dbfc47/go/oasis-test-runner/scenario/e2e/e2e.go#L58

Though I agree that current usage is kind of tricky. `Parameters()` should also support flags defined in non-Var manner as you proposed and in this case flags themselves **must** be struct fields. Cloning will be a bit more complicated then. I will look into it.
