### ISSUE TITLE
Support runtime versions in registry

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-core#2916]
For supporting key-manager upgrades, having at least 2 versions of the keymanager runtime is required. This is needed since for the upgrade period new nodes need to replicate state from the old nodes which requires both new and old nodes need to be registered.

**Comment by Yawning** [comment]
```
// VersionInfoIntelSGX is the SGX TEE version information.
type VersionInfoIntelSGX struct {
	// Enclaves is the allowed MRENCLAVE/MRSIGNER pairs.
	Enclaves []sgx.EnclaveIdentity `json:"enclaves"`
}
```

The enclave identities associated with a runtime, is a slice for a reason.

**Comment by ptrus** [comment]
yeah: https://github.com/oasislabs/oasis-core/blob/3c86d9529078b524ebe1d1923df5697617afce5f/go/registry/api/runtime.go#L271-L274 is probaby good enough
