### ISSUE TITLE
oasis-node crashes, if metrics in push mode and PGW crashes

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2936]
Currently, if oasis-node is run in metrics push mode and push gateway unexpectedly crashes, so does oasis-node.

Improve oasis-node Prometheus pusher code as follows:
1. If PGW is not responding, try to reconnect.
2. When starting oasis-node in push mode and if PGW is not accessible, try to reconnect instead of failing to start.

**Comment by kostko** [comment]
How does it crash, any stack traces?

**Comment by Yawning** [comment]
> If PGW is not responding, try to reconnect.

Make the upstream code not brain-damaged then.

https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/push?tab=doc#Pusher.Push
