### ISSUE TITLE
oasis-node doesn't parse signer related flags

### ISSUE THREAD

**Issue by raynaudoe** [oasislabs/oasis-core#2950]
##### SUMMARY
Passing --signer flag to oasis-node will throw: 
`unknown flag: --signer`

##### ISSUE TYPE
- Bug Report

##### OASIS NODE VERSION

```Software version: 20.6
Runtime protocol version: 0.13.0
Consensus protocol version: 0.25.0
Committee protocol version: 0.9.0
Tendermint core version: 0.33.4
ABCI library version: 0.16.2
Go toolchain version: 1.14.3
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
oasis-node --config ./etc/config.yml --signer file 

##### ACTUAL RESULTS

```
unknown flag: --signer
```

##### EXPECTED RESULTS
All signer related configs should be correctly parsed.

**Comment by kostko** [comment]
Thanks for reporting this, it should be fixed by #2951.
