### ISSUE TITLE
Extend cargo ekiden shell to support AWS docker instances

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-core#595]
Currently, the `canonical` environment for development is the docker development instance. Our cargo tool allows instantiating this locally, but it would also be useful to allow a shell to be spun up on AWS.

We have a python script that does some of that tooling, but it doesn't reproduce the environment.
In particular:
* [ ] Have the same mounted `/code` directory sync'ed to the local workspace.
* [ ] Ideally use ECS (the container service) rather than a full EC2 instance.
* [ ] Run as part of `cargo ekiden shell`

**Comment by kostko** [comment]
No longer exists.
