### ISSUE TITLE
Truffle migrate in CI is flaky

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-core#613]
The truffle migrate step to have ethereum addresses of contracts for test-e2e is sometimes failing

http://email.circleci.com/c/eJw9T8tqwzAQ_Br5ZmNLliwdfAgpORZi6DlIKyXeVA9jyfT3q5S2sCyzMzAza2cplGxwXrxP19O4oFUsqPvH-z4u5toNnA2Uy2mSXCoy9lvKRfsOt3boW8bagY3t1DmgHcbi9qh9s84wcgnTxBg1XEOvjFQGhJBSUFBcisbPaylbJuxE6KUO4A7eAXaQQj0fa11JZ8xem1yx-0TrYgWUsoGwy1HCDXTYND4iYW_mQG_bu0bvLKHipQZn8QhVc6HSv2ROxw6ukjEVvCPogik2-_yF3tff_hNfNZoy_9jW-POf8zmm2_OIWL4B8dBjsg

**Comment by Yawning** [comment]
Truffle migrate is not in CI.
