### ISSUE TITLE
`cargo ekiden shell` resumes container without checking docker_image

### ISSUE THREAD

**Issue by bl4ck5un** [oasislabs/oasis-core#727]
After upgrading to a new docker image, `cargo ekiden shell` still resumes the container with the old image instead of creating a new one.

https://github.com/oasislabs/ekiden/blob/593b3f4dae1c03085fbbae9ddb6ec37622a80dc0/tools/src/command_shell.rs#L153-L157 only checks `docker-name`. It should also check against `docker-image`.

**Comment by kostko** [comment]
No longer exists.
