### ISSUE TITLE
Automatically generate the changelog

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#759]
We should consider automatically generating the changelog.

**Comment by tjanez** [comment]
## Implementation proposal

Each pull request that is made to the Oasis Core repo should generally include a Changelog fragment in the `newsfragments/` directory.

Before a release, all news fragments are automatically assembled into the Changelog file using the [towncrier](https://github.com/hawkowl/towncrier) utility and committed into the repo.

Examples of news fragments of (some) popular projects using towncrier:
- pip: https://github.com/pypa/pip/tree/db1a2754bb2aa4f92db781933661c170100f154f/news
- Pipenv: https://github.com/pypa/pipenv/tree/5b6bfc96b5e50011a796ea6c3cc476b7909f38b1/news
- Buildbot: https://github.com/buildbot/buildbot/tree/d2aa5a659305562bc9742afdd03c291fc83e468e/master/buildbot/newsfragments
- Trio: https://github.com/python-trio/trio/tree/master/newsfragments
- Telepresence: https://github.com/telepresenceio/telepresence/tree/bb2eb584cc25deba7e5920938d576693c847bed0/newsfragments

Although it is geared towards Python projects and works with rST by default, it can be made to [work with Markdown](https://github.com/hawkowl/towncrier/issues/128) and [for non-Python projects](https://github.com/hawkowl/towncrier/pull/166).
