### ISSUE TITLE
Zero-copy protobuf

### ISSUE THREAD

**Issue by ryscheng** [oasislabs/oasis-core#9]
Actually, it seems that our Protocol Buffers implementation does support zero-copy using the bytes feature. https://github.com/stepancheg/rust-protobuf#copy-on-write

There is of course also the problem of security - when crossing enclave boundaries things should be copied at one point to avoid untrusted memory mutations while the enclave is executing, possibly violating security.

**Comment by Yawning** [comment]
We no longer use protobufs for enclave communication.
